print("Christmas in the City: A Mad Lib")
print("Instructions: The program will ask for a type of word to be entered.  Afterall the words are entered, the program will tell a story.")
last_name = input("Enter a last name. ")
male_first_name = input("Enter a male first name. ")
part_of_a_building = input("Enter a part of a bulding. ")
adjective = input("Enter an adjective. ")
adjective2 = input("Enter an adjective. ")
place = input("Enter a place. ")
number = input("Enter a number. ")
noun = input("Enter a noun. ")
noun2 = input("Enter a noun. ")
noun3 = input("Enter a noun. ")
type_of_weather = input("Enter a type of weather. ")
emotion = input("Enter an emotion. ")
type_of_clothing = input("Enter a type of clothing. ")
type_of_clothing2 = input("Enter a type of clothing. ")
adjective3 = input("Enter an adjective. ")

print(f"Christmas was coming soon, and everyone was getting ready. There were meals being prepared and presents being wrapped. The {last_name} family was also getting ready. They were busy running around the city, buying gifts and groceries. {male_first_name}, the youngest of the family, was busy looking outside the {part_of_a_building}. Outside, it was {adjective} and {adjective2}, due to the fact that they lived in {place}. Oh, how he longed to see snow. It has been {number} years since he was born, but he hasn't seen snow at all. He didn't travel because his {noun} also lived in {place}. It was Christmas Eve and {male_first_name}'s bedtime. Before he went to bed, he made a little {noun2}. He wished to be able to see snow, even if it was only one time. Then he drifted off to sleep.")
print(f"Christmas day, {male_first_name} got up and headed downstairs. He saw gifts under the {noun3}, but that wasn't what caught his eye. He looked at the window and saw little flakes of {type_of_weather}.  He was very {emotion}. He quickly went to his room and got dressed. He grabbed his warmest {type_of_clothing} and {type_of_clothing2}. He went back downstaris and out the door. He started playing in the snow. It was truly a {adjective3} day for {male_first_name}.")
